routes/web.php
<?php
//use App\Category; //para prueba de carga de categorias en sesion
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Route::get('/', function () {
    return view('welcome');
}); */
Route::redirect('/', 'blog');

Auth::routes();

//*************** Web (rutas para clientes (invitados)) ********************//

//muestra listado de posts
Route::get('/blog', 'Web\PageController@blog')->name('blog'); //la ruta se va a llamar blog

// * Prueba de redireccion a metodo de controller con previa carga de datos (categorias) en sesion
/*Route::get('/blog', function() {
    if (empty(session('categories'))) {
        session(['count' => $count,'categories' => Category::all()]);
    }  
    return redirect()->action('Web\PageController@blog');
});
//se necesita una ruta para el metodo del controller
Route::get('/bloglist', 'Web\PageController@blog');//->name('blog'); //la ruta se va a llamar blog
*/

//permite ver detalles de un post particular al presionar el link 'Leer mas' de la view
//posts.blade.php. Recibe parametro 'slug'
Route::get('/entrada/{slug}', 'Web\PageController@post')->name('post');

//ruta para filtrado por categorias (al presionar link de la categoria de un post en su detalle)
Route::get('/categoria/{slug}', 'Web\PageController@category')->name('category');
//ruta para filtrado por etiquetas (al presionar link de etiqueta de un post en su detalle )
Route::get('/etiqueta/{slug}', 'Web\PageController@tag')->name('tag');

//*************************** Admin (rutas para la parte adminsitrativa) ***************************/

//cruds de tags, categorias y posts. Con cad resource ya se generan 7 rutas para cada
//nombre de url 
Route::resource('tags', 'Admin\TagController');
Route::resource('categories', 'Admin\CategoryController');
Route::resource('posts', 'Admin\PostController');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <!-- css bootstrap -->
    {{-- <link href="{{asset('cssBootstrap/bootstrap.min.css')}}" rel="stylesheet"> --}}
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        <li><a href="{{ route('blog') }}">Blog</a></li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest {{-- si es invitado muestro links de login y registro --}}
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else {{-- usuario logueado --}}
                            {{-- Agregado de botones --}}
                            <li><a href="{{ route('tags.index') }}">Etiquetas</a></li>
                            <li><a href="{{ route('categories.index') }}">Categorías</a></li>
                            <li><a href="{{ route('posts.index') }}">Entradas</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        {{-- Agregado: alert para mostrar mensajes al obtener el response desde el server para cruds --}}
        @if(session('info')) {{-- info es parametro (clave) de sesion flash --}}
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <div class="alert alert-success">
                            {{ session('info') }}
                        </div>
                    </div>
                </div>
            </div>
        @endif

        {{-- Agregado: para mostrar errores. $errors es una variable global --}}
        @if(count($errors))
            <div class="container">
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2">
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
        @endif

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    <!-- js bootstrap -->
    <script src="{{asset('jsBootstrap/jquery-3.3.1.min.js')}}"></script> 
    <script src="{{asset('jsBootstrap/bootstrap.min.js')}}"></script>

    {{-- Agregado: para carga de tag <script> (en index.blade.php de view tag), para cargar 
        codigo js con ajax. Se usa la @section correspondiente en index.blade.php --}}    
    @yield('script-ajax') {{-- colocamos estas secciones para colocar js personalizado en la view que se quiera --}}

    @yield('scripts')
</body>
</html>